name = "detour-web"
account_id = "a92a6db0c65c8a9fc0bd0b2ce3da4276"
compatibility_date = "2026-06-22"

workers_dev = true

routes = [
  { pattern = "takedetour.app", custom_domain = true },
  { pattern = "new.takedetour.app", custom_domain = true }
]

[assets]
directory = "./public"
not_found_handling = "single-page-application"
