/// <reference path="../pb_data/types.d.ts" />
//
// Detour baseline schema — every collection the app owns, in one place.
//
// This replaces the entire previous migration history. That history recorded how
// Detour got here rather than what it is: an external-guide catalogue (Guía
// Repsol, Michelin, 50 Top Pizza, the World's 100 Best Coffee Shops), a v1
// itinerary model (`detours`, `places`), an editorial lane, per-source
// provenance tables, and an award collection — all of it seeded, then amended,
// then swept away again across ~90 files. Replaying that to reach an empty
// clean state meant recreating thousands of rows only to delete them, which is
// both slow at boot and the documented boot-loop risk on a shared VM.
//
// What Detour actually is, and all this file declares:
//
//   members                      the invite-only circle
//   invites / invite_requests    how someone joins it
//   cities                       the destinations places are routed under
//   venues                       place facts, occasion tags, and the publication
//                                marker (`published`, `published_at`,
//                                `suppressed`) — no awards, no guide sources
//   community_waitlist_entries   the place a recommendation attaches to
//   community_recommendations    the recommendation itself — the ONLY reason
//                                anything is public on Detour
//   community_shares / _replies  private member-to-member sends
//   member_place_contributions   the legacy curator-reviewed contribution lane
//   detour_submissions           the curator publication lane
//   visit_evidence               private proof a member actually went
//   founding_feedback_responses  the founding-member survey
//
// Platform-managed collections (`supernaut_payments_settings`,
// `supernaut_products`, `supernaut_customers`, `supernaut_subscriptions`,
// `supernaut_payments`) are deliberately absent: the Supernaut platform
// provisions and maintains those, and app migrations must never touch them.
//
// Idempotent by construction. `importCollections(…, false)` creates what is
// missing and updates what exists without deleting anything unlisted, so this is
// safe both on a clean volume and against a database that already carries the
// schema — collection and field ids are pinned below, so an existing install is
// matched by id rather than duplicated.
migrate((app) => {
  const collections = [
    {
      "id": "pbc_3998141477",
      "name": "cities",
      "type": "base",
      "system": false,
      "fields": [
        {
          "autogeneratePattern": "[a-z0-9]{15}",
          "help": "",
          "hidden": false,
          "id": "text3208210256",
          "max": 15,
          "min": 15,
          "name": "id",
          "pattern": "^[a-z0-9]+$",
          "presentable": false,
          "primaryKey": true,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text1579384326",
          "max": 120,
          "min": 0,
          "name": "name",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": false,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text2560465762",
          "max": 120,
          "min": 0,
          "name": "slug",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": false,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text1400097126",
          "max": 120,
          "min": 0,
          "name": "country",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": false,
          "type": "text"
        },
        {
          "help": "",
          "hidden": false,
          "id": "select2607212691",
          "maxSelect": 1,
          "name": "presentation",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "select",
          "values": [
            "map",
            "list"
          ]
        },
        {
          "help": "",
          "hidden": false,
          "id": "number820951658",
          "max": null,
          "min": null,
          "name": "center_lat",
          "onlyInt": false,
          "presentable": false,
          "required": false,
          "system": false,
          "type": "number"
        },
        {
          "help": "",
          "hidden": false,
          "id": "number868804475",
          "max": null,
          "min": null,
          "name": "center_lng",
          "onlyInt": false,
          "presentable": false,
          "required": false,
          "system": false,
          "type": "number"
        },
        {
          "help": "",
          "hidden": false,
          "id": "number3073079668",
          "max": null,
          "min": null,
          "name": "zoom",
          "onlyInt": false,
          "presentable": false,
          "required": false,
          "system": false,
          "type": "number"
        },
        {
          "help": "",
          "hidden": false,
          "id": "number4166822869",
          "max": null,
          "min": null,
          "name": "bounds_lat_min",
          "onlyInt": false,
          "presentable": false,
          "required": false,
          "system": false,
          "type": "number"
        },
        {
          "help": "",
          "hidden": false,
          "id": "number3293680780",
          "max": null,
          "min": null,
          "name": "bounds_lat_max",
          "onlyInt": false,
          "presentable": false,
          "required": false,
          "system": false,
          "type": "number"
        },
        {
          "help": "",
          "hidden": false,
          "id": "number776664146",
          "max": null,
          "min": null,
          "name": "bounds_lng_min",
          "onlyInt": false,
          "presentable": false,
          "required": false,
          "system": false,
          "type": "number"
        },
        {
          "help": "",
          "hidden": false,
          "id": "number306694923",
          "max": null,
          "min": null,
          "name": "bounds_lng_max",
          "onlyInt": false,
          "presentable": false,
          "required": false,
          "system": false,
          "type": "number"
        }
      ],
      "indexes": [
        "CREATE UNIQUE INDEX `idx_cities_slug` ON `cities` (slug)"
      ],
      "listRule": "",
      "viewRule": "",
      "createRule": null,
      "updateRule": null,
      "deleteRule": null
    },
    {
      "id": "pbc_1760521077",
      "name": "community_recommendations",
      "type": "base",
      "system": false,
      "fields": [
        {
          "autogeneratePattern": "[a-z0-9]{15}",
          "help": "",
          "hidden": false,
          "id": "text3208210256",
          "max": 15,
          "min": 15,
          "name": "id",
          "pattern": "^[a-z0-9]+$",
          "presentable": false,
          "primaryKey": true,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "cascadeDelete": true,
          "collectionId": "pbc_3750161679",
          "help": "",
          "hidden": false,
          "id": "relation2824027944",
          "maxSelect": 1,
          "minSelect": 0,
          "name": "waitlist",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "relation"
        },
        {
          "cascadeDelete": true,
          "collectionId": "pbc_2620428958",
          "help": "",
          "hidden": true,
          "id": "relation1894054520",
          "maxSelect": 1,
          "minSelect": 0,
          "name": "member",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "relation"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text3485334036",
          "max": 2400,
          "min": 0,
          "name": "note",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": false,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text3892671406",
          "max": 200,
          "min": 0,
          "name": "venue_name",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text760939060",
          "max": 120,
          "min": 0,
          "name": "city",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text1400097126",
          "max": 120,
          "min": 0,
          "name": "country",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "hidden": false,
          "id": "autodate2990389176",
          "name": "created",
          "onCreate": true,
          "onUpdate": false,
          "presentable": false,
          "system": false,
          "type": "autodate"
        },
        {
          "hidden": false,
          "id": "autodate3332085495",
          "name": "updated",
          "onCreate": true,
          "onUpdate": true,
          "presentable": false,
          "system": false,
          "type": "autodate"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text223244161",
          "max": 300,
          "min": 0,
          "name": "address",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "help": "",
          "hidden": false,
          "id": "select105650625",
          "maxSelect": 1,
          "name": "category",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "select",
          "values": [
            "restaurant",
            "cafe",
            "bakery",
            "bar",
            "cocktail_bar",
            "wine_bar",
            "brewery",
            "food_market",
            "deli",
            "dessert_shop",
            "ice_cream",
            "takeaway",
            "other"
          ]
        },
        {
          "help": "",
          "hidden": false,
          "id": "select3420765984",
          "maxSelect": 14,
          "name": "occasions",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "select",
          "values": [
            "celebration",
            "casual_local_favorite",
            "coffee",
            "bakery",
            "drinks_nightcap",
            "neighborhood_meal",
            "date_night",
            "group_gathering",
            "quick_bite",
            "breakfast_brunch",
            "solo_friendly",
            "family_friendly",
            "late_night",
            "outdoor_seating"
          ]
        }
      ],
      "indexes": [
        "CREATE UNIQUE INDEX `idx_community_recommendations_member_waitlist` ON `community_recommendations` (member, waitlist)",
        "CREATE INDEX `idx_community_recommendations_waitlist` ON `community_recommendations` (waitlist)"
      ],
      "listRule": "@request.auth.id != '' && member = @request.auth.id",
      "viewRule": "@request.auth.id != '' && member = @request.auth.id",
      "createRule": "@request.auth.id != '' && @request.auth.community_status = 'verified'",
      "updateRule": "@request.auth.id != '' && member = @request.auth.id",
      "deleteRule": "@request.auth.id != '' && member = @request.auth.id"
    },
    {
      "id": "pbc_3553174971",
      "name": "community_share_replies",
      "type": "base",
      "system": false,
      "fields": [
        {
          "autogeneratePattern": "[a-z0-9]{15}",
          "help": "",
          "hidden": false,
          "id": "text3208210256",
          "max": 15,
          "min": 15,
          "name": "id",
          "pattern": "^[a-z0-9]+$",
          "presentable": false,
          "primaryKey": true,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "cascadeDelete": true,
          "collectionId": "pbc_4294588938",
          "help": "",
          "hidden": false,
          "id": "relation4010188122",
          "maxSelect": 1,
          "minSelect": 0,
          "name": "share",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "relation"
        },
        {
          "cascadeDelete": true,
          "collectionId": "pbc_2620428958",
          "help": "",
          "hidden": false,
          "id": "relation3182418120",
          "maxSelect": 1,
          "minSelect": 0,
          "name": "author",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "relation"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": true,
          "id": "text3133994713",
          "max": 100,
          "min": 0,
          "name": "author_name",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": false,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text1661960112",
          "max": 30,
          "min": 0,
          "name": "author_pseudo",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": false,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text3685223346",
          "max": 1200,
          "min": 0,
          "name": "body",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": false,
          "type": "text"
        },
        {
          "hidden": false,
          "id": "autodate2990389176",
          "name": "created",
          "onCreate": true,
          "onUpdate": false,
          "presentable": false,
          "system": false,
          "type": "autodate"
        },
        {
          "hidden": false,
          "id": "autodate3332085495",
          "name": "updated",
          "onCreate": true,
          "onUpdate": true,
          "presentable": false,
          "system": false,
          "type": "autodate"
        }
      ],
      "indexes": [
        "CREATE INDEX `idx_community_share_replies_share_created` ON `community_share_replies` (share, created)",
        "CREATE INDEX `idx_community_share_replies_author_created` ON `community_share_replies` (author, created)"
      ],
      "listRule": "@request.auth.id != '' && (share.sender = @request.auth.id || share.recipient = @request.auth.id)",
      "viewRule": "@request.auth.id != '' && (share.sender = @request.auth.id || share.recipient = @request.auth.id)",
      "createRule": "@request.auth.id != '' && @request.auth.community_status = 'verified'",
      "updateRule": null,
      "deleteRule": null
    },
    {
      "id": "pbc_4294588938",
      "name": "community_shares",
      "type": "base",
      "system": false,
      "fields": [
        {
          "autogeneratePattern": "[a-z0-9]{15}",
          "help": "",
          "hidden": false,
          "id": "text3208210256",
          "max": 15,
          "min": 15,
          "name": "id",
          "pattern": "^[a-z0-9]+$",
          "presentable": false,
          "primaryKey": true,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "cascadeDelete": true,
          "collectionId": "pbc_2620428958",
          "help": "",
          "hidden": false,
          "id": "relation1593854671",
          "maxSelect": 1,
          "minSelect": 0,
          "name": "sender",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "relation"
        },
        {
          "cascadeDelete": true,
          "collectionId": "pbc_2620428958",
          "help": "",
          "hidden": false,
          "id": "relation1745156937",
          "maxSelect": 1,
          "minSelect": 0,
          "name": "recipient",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "relation"
        },
        {
          "cascadeDelete": true,
          "collectionId": "pbc_3750161679",
          "help": "",
          "hidden": false,
          "id": "relation2824027944",
          "maxSelect": 1,
          "minSelect": 0,
          "name": "waitlist",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "relation"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text4273470761",
          "max": 1200,
          "min": 0,
          "name": "personal_note",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": false,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text3892671406",
          "max": 200,
          "min": 0,
          "name": "venue_name",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text760939060",
          "max": 120,
          "min": 0,
          "name": "city",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text1400097126",
          "max": 120,
          "min": 0,
          "name": "country",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "hidden": false,
          "id": "autodate2990389176",
          "name": "created",
          "onCreate": true,
          "onUpdate": false,
          "presentable": false,
          "system": false,
          "type": "autodate"
        },
        {
          "hidden": false,
          "id": "autodate3332085495",
          "name": "updated",
          "onCreate": true,
          "onUpdate": true,
          "presentable": false,
          "system": false,
          "type": "autodate"
        },
        {
          "cascadeDelete": true,
          "collectionId": "pbc_1379753955",
          "help": "",
          "hidden": false,
          "id": "relation2442205965",
          "maxSelect": 1,
          "minSelect": 0,
          "name": "venue",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "relation"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": true,
          "id": "text2714339541",
          "max": 100,
          "min": 0,
          "name": "sender_name",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": true,
          "id": "text2913987824",
          "max": 100,
          "min": 0,
          "name": "recipient_name",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "help": "",
          "hidden": false,
          "id": "bool2756839960",
          "name": "seen",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "bool"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text223244161",
          "max": 300,
          "min": 0,
          "name": "address",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text2013755266",
          "max": 30,
          "min": 0,
          "name": "sender_pseudo",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text3660254786",
          "max": 30,
          "min": 0,
          "name": "recipient_pseudo",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "help": "",
          "hidden": false,
          "id": "bool1639016958",
          "name": "archived",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "bool"
        },
        {
          "help": "",
          "hidden": false,
          "id": "bool1837794304",
          "name": "sender_archived",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "bool"
        }
      ],
      "indexes": [
        "CREATE INDEX `idx_community_shares_sender` ON `community_shares` (sender)",
        "CREATE INDEX `idx_community_shares_recipient` ON `community_shares` (recipient)",
        "CREATE INDEX `idx_community_shares_waitlist` ON `community_shares` (waitlist)"
      ],
      "listRule": "@request.auth.id != '' && (sender = @request.auth.id || recipient = @request.auth.id)",
      "viewRule": "@request.auth.id != '' && (sender = @request.auth.id || recipient = @request.auth.id)",
      "createRule": "@request.auth.id != '' && @request.auth.community_status = 'verified'",
      "updateRule": "@request.auth.id != '' && (sender = @request.auth.id || recipient = @request.auth.id)",
      "deleteRule": "@request.auth.id != '' && sender = @request.auth.id"
    },
    {
      "id": "pbc_3750161679",
      "name": "community_waitlist_entries",
      "type": "base",
      "system": false,
      "fields": [
        {
          "autogeneratePattern": "[a-z0-9]{15}",
          "help": "",
          "hidden": false,
          "id": "text3208210256",
          "max": 15,
          "min": 15,
          "name": "id",
          "pattern": "^[a-z0-9]+$",
          "presentable": false,
          "primaryKey": true,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text3892671406",
          "max": 200,
          "min": 0,
          "name": "venue_name",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": false,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text760939060",
          "max": 120,
          "min": 0,
          "name": "city",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": false,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text1400097126",
          "max": 120,
          "min": 0,
          "name": "country",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": false,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": true,
          "id": "text3600548136",
          "max": 240,
          "min": 0,
          "name": "normalized_name",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": false,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": true,
          "id": "text2783214874",
          "max": 160,
          "min": 0,
          "name": "normalized_city",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": false,
          "type": "text"
        },
        {
          "help": "",
          "hidden": false,
          "id": "select2063623452",
          "maxSelect": 1,
          "name": "status",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "select",
          "values": [
            "pending",
            "published"
          ]
        },
        {
          "help": "",
          "hidden": false,
          "id": "number1249310464",
          "max": null,
          "min": 0,
          "name": "signal_count",
          "onlyInt": true,
          "presentable": false,
          "required": false,
          "system": false,
          "type": "number"
        },
        {
          "cascadeDelete": false,
          "collectionId": "pbc_2620428958",
          "help": "",
          "hidden": true,
          "id": "relation1902735506",
          "maxSelect": 1000,
          "minSelect": 0,
          "name": "participants",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "relation"
        },
        {
          "cascadeDelete": false,
          "collectionId": "pbc_1379753955",
          "help": "",
          "hidden": true,
          "id": "relation2333317334",
          "maxSelect": 1,
          "minSelect": 0,
          "name": "canonical_venue",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "relation"
        },
        {
          "cascadeDelete": false,
          "collectionId": "pbc_1379753955",
          "help": "",
          "hidden": true,
          "id": "relation1618046846",
          "maxSelect": 1,
          "minSelect": 0,
          "name": "published_venue",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "relation"
        },
        {
          "help": "",
          "hidden": true,
          "id": "date3772055009",
          "max": "",
          "min": "",
          "name": "published_at",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "date"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": true,
          "id": "text2454586888",
          "max": 100,
          "min": 0,
          "name": "publication_audit_id",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "hidden": false,
          "id": "autodate2990389176",
          "name": "created",
          "onCreate": true,
          "onUpdate": false,
          "presentable": false,
          "system": false,
          "type": "autodate"
        },
        {
          "hidden": false,
          "id": "autodate3332085495",
          "name": "updated",
          "onCreate": true,
          "onUpdate": true,
          "presentable": false,
          "system": false,
          "type": "autodate"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text223244161",
          "max": 300,
          "min": 0,
          "name": "address",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "help": "",
          "hidden": false,
          "id": "select105650625",
          "maxSelect": 1,
          "name": "category",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "select",
          "values": [
            "restaurant",
            "cafe",
            "bakery",
            "bar",
            "cocktail_bar",
            "wine_bar",
            "brewery",
            "food_market",
            "deli",
            "dessert_shop",
            "ice_cream",
            "takeaway",
            "other"
          ]
        },
        {
          "help": "",
          "hidden": false,
          "id": "select3420765984",
          "maxSelect": 14,
          "name": "occasions",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "select",
          "values": [
            "celebration",
            "casual_local_favorite",
            "coffee",
            "bakery",
            "drinks_nightcap",
            "neighborhood_meal",
            "date_night",
            "group_gathering",
            "quick_bite",
            "breakfast_brunch",
            "solo_friendly",
            "family_friendly",
            "late_night",
            "outdoor_seating"
          ]
        },
        {
          "exceptDomains": null,
          "help": "",
          "hidden": false,
          "id": "url4063379760",
          "name": "official_url",
          "onlyDomains": null,
          "presentable": false,
          "required": false,
          "system": false,
          "type": "url"
        },
        {
          "exceptDomains": null,
          "help": "",
          "hidden": false,
          "id": "url260122942",
          "name": "instagram_url",
          "onlyDomains": null,
          "presentable": false,
          "required": false,
          "system": false,
          "type": "url"
        },
        {
          "exceptDomains": null,
          "help": "",
          "hidden": false,
          "id": "url2895943165",
          "name": "image_url",
          "onlyDomains": null,
          "presentable": false,
          "required": false,
          "system": false,
          "type": "url"
        },
        {
          "help": "",
          "hidden": true,
          "id": "date2999186953",
          "max": "",
          "min": "",
          "name": "publication_notification_sent_at",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "date"
        }
      ],
      "indexes": [
        "CREATE UNIQUE INDEX `idx_community_waitlist_normalized_place` ON `community_waitlist_entries` (normalized_name, normalized_city)",
        "CREATE INDEX `idx_community_waitlist_status` ON `community_waitlist_entries` (status)"
      ],
      "listRule": "@request.auth.id != '' && participants.id ?= @request.auth.id",
      "viewRule": "@request.auth.id != '' && participants.id ?= @request.auth.id",
      "createRule": null,
      "updateRule": "@request.auth.id != '' && participants.id ?= @request.auth.id",
      "deleteRule": null
    },
    {
      "id": "pbc_3583178514",
      "name": "detour_submissions",
      "type": "base",
      "system": false,
      "fields": [
        {
          "autogeneratePattern": "[a-z0-9]{15}",
          "help": "",
          "hidden": false,
          "id": "text3208210256",
          "max": 15,
          "min": 15,
          "name": "id",
          "pattern": "^[a-z0-9]+$",
          "presentable": false,
          "primaryKey": true,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "cascadeDelete": true,
          "collectionId": "pbc_2620428958",
          "help": "",
          "hidden": false,
          "id": "relation1894054520",
          "maxSelect": 1,
          "minSelect": 0,
          "name": "member",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "relation"
        },
        {
          "cascadeDelete": false,
          "collectionId": "pbc_1379753955",
          "help": "",
          "hidden": false,
          "id": "relation2442205965",
          "maxSelect": 1,
          "minSelect": 0,
          "name": "venue",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "relation"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text3892671406",
          "max": 200,
          "min": 0,
          "name": "venue_name",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": false,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text760939060",
          "max": 120,
          "min": 0,
          "name": "city",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": false,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text223244161",
          "max": 300,
          "min": 0,
          "name": "address",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text3032520184",
          "max": 2400,
          "min": 0,
          "name": "detour_note",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": false,
          "type": "text"
        },
        {
          "exceptDomains": null,
          "help": "",
          "hidden": false,
          "id": "url2776776943",
          "name": "source_url",
          "onlyDomains": null,
          "presentable": false,
          "required": false,
          "system": false,
          "type": "url"
        },
        {
          "help": "",
          "hidden": false,
          "id": "select2063623452",
          "maxSelect": 1,
          "name": "status",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "select",
          "values": [
            "pending",
            "approved",
            "rejected",
            "published"
          ]
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": true,
          "id": "text1434203354",
          "max": 1200,
          "min": 0,
          "name": "curator_note",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "hidden": false,
          "id": "autodate2990389176",
          "name": "created",
          "onCreate": true,
          "onUpdate": false,
          "presentable": false,
          "system": false,
          "type": "autodate"
        },
        {
          "hidden": false,
          "id": "autodate3332085495",
          "name": "updated",
          "onCreate": true,
          "onUpdate": true,
          "presentable": false,
          "system": false,
          "type": "autodate"
        },
        {
          "cascadeDelete": false,
          "collectionId": "pbc_1379753955",
          "help": "",
          "hidden": true,
          "id": "relation1618046846",
          "maxSelect": 1,
          "minSelect": 0,
          "name": "published_venue",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "relation"
        },
        {
          "help": "",
          "hidden": true,
          "id": "date3772055009",
          "max": "",
          "min": "",
          "name": "published_at",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "date"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": true,
          "id": "text2454586888",
          "max": 80,
          "min": 0,
          "name": "publication_audit_id",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        }
      ],
      "indexes": [
        "CREATE INDEX IF NOT EXISTS idx_detour_submissions_member_status ON detour_submissions (member, status)"
      ],
      "listRule": "@request.auth.id != '' && member = @request.auth.id",
      "viewRule": "@request.auth.id != '' && member = @request.auth.id",
      "createRule": "@request.auth.id != '' && @request.auth.community_status = 'verified'",
      "updateRule": null,
      "deleteRule": null
    },
    {
      "id": "pbc_3578545153",
      "name": "founding_feedback_responses",
      "type": "base",
      "system": false,
      "fields": [
        {
          "autogeneratePattern": "[a-z0-9]{15}",
          "help": "",
          "hidden": false,
          "id": "text3208210256",
          "max": 15,
          "min": 15,
          "name": "id",
          "pattern": "^[a-z0-9]+$",
          "presentable": false,
          "primaryKey": true,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "help": "",
          "hidden": false,
          "id": "select1034975820",
          "maxSelect": 1,
          "name": "discovery_source",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "select",
          "values": [
            "friends",
            "food-people",
            "social",
            "reviews",
            "other"
          ]
        },
        {
          "help": "",
          "hidden": false,
          "id": "select3934825281",
          "maxSelect": 1,
          "name": "circle_interest",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "select",
          "values": [
            "yes",
            "maybe",
            "no"
          ]
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text1876833823",
          "max": 1200,
          "min": 8,
          "name": "value_needed",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": false,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": true,
          "id": "text1602912115",
          "max": 40,
          "min": 0,
          "name": "source",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": false,
          "type": "text"
        }
      ],
      "indexes": [],
      "listRule": null,
      "viewRule": null,
      "createRule": null,
      "updateRule": null,
      "deleteRule": null
    },
    {
      "id": "pbc_2936470090",
      "name": "invite_requests",
      "type": "base",
      "system": false,
      "fields": [
        {
          "autogeneratePattern": "[a-z0-9]{15}",
          "help": "",
          "hidden": false,
          "id": "text3208210256",
          "max": 15,
          "min": 15,
          "name": "id",
          "pattern": "^[a-z0-9]+$",
          "presentable": false,
          "primaryKey": true,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "exceptDomains": null,
          "help": "",
          "hidden": false,
          "id": "email3885137012",
          "name": "email",
          "onlyDomains": null,
          "presentable": false,
          "required": true,
          "system": false,
          "type": "email"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text1579384326",
          "max": 120,
          "min": 0,
          "name": "name",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text760939060",
          "max": 120,
          "min": 0,
          "name": "city",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text704810992",
          "max": 500,
          "min": 0,
          "name": "why",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text1602912115",
          "max": 120,
          "min": 0,
          "name": "source",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "help": "",
          "hidden": false,
          "id": "select2063623452",
          "maxSelect": 1,
          "name": "status",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "select",
          "values": [
            "new",
            "invited",
            "declined"
          ]
        },
        {
          "hidden": false,
          "id": "autodate2990389176",
          "name": "created",
          "onCreate": true,
          "onUpdate": false,
          "presentable": false,
          "system": false,
          "type": "autodate"
        },
        {
          "hidden": false,
          "id": "autodate3332085495",
          "name": "updated",
          "onCreate": true,
          "onUpdate": true,
          "presentable": false,
          "system": false,
          "type": "autodate"
        }
      ],
      "indexes": [
        "CREATE UNIQUE INDEX `idx_invite_requests_email` ON `invite_requests` (email)"
      ],
      "listRule": null,
      "viewRule": null,
      "createRule": "",
      "updateRule": null,
      "deleteRule": null
    },
    {
      "id": "pbc_2452428166",
      "name": "invites",
      "type": "base",
      "system": false,
      "fields": [
        {
          "autogeneratePattern": "[a-z0-9]{15}",
          "help": "",
          "hidden": false,
          "id": "text3208210256",
          "max": 15,
          "min": 15,
          "name": "id",
          "pattern": "^[a-z0-9]+$",
          "presentable": false,
          "primaryKey": true,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "cascadeDelete": true,
          "collectionId": "pbc_2620428958",
          "help": "",
          "hidden": false,
          "id": "relation1310577343",
          "maxSelect": 1,
          "minSelect": 0,
          "name": "issued_by",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "relation"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text1997877400",
          "max": 80,
          "min": 0,
          "name": "code",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": false,
          "type": "text"
        },
        {
          "cascadeDelete": true,
          "collectionId": "pbc_2620428958",
          "help": "",
          "hidden": false,
          "id": "relation694952315",
          "maxSelect": 1,
          "minSelect": 0,
          "name": "claimed_by",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "relation"
        },
        {
          "help": "",
          "hidden": false,
          "id": "date2096107013",
          "max": "",
          "min": "",
          "name": "claimed_at",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "date"
        },
        {
          "hidden": false,
          "id": "autodate2990389176",
          "name": "created",
          "onCreate": true,
          "onUpdate": false,
          "presentable": false,
          "system": false,
          "type": "autodate"
        },
        {
          "hidden": false,
          "id": "autodate3332085495",
          "name": "updated",
          "onCreate": true,
          "onUpdate": true,
          "presentable": false,
          "system": false,
          "type": "autodate"
        }
      ],
      "indexes": [
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_invites_code ON invites (code)",
        "CREATE INDEX IF NOT EXISTS idx_invites_issued_by ON invites (issued_by)",
        "CREATE INDEX IF NOT EXISTS idx_invites_claimed_by ON invites (claimed_by)"
      ],
      "listRule": "@request.auth.id != '' && (issued_by = @request.auth.id || claimed_by = @request.auth.id)",
      "viewRule": "@request.auth.id != '' && (issued_by = @request.auth.id || claimed_by = @request.auth.id)",
      "createRule": "@request.auth.id != ''",
      "updateRule": null,
      "deleteRule": null
    },
    {
      "id": "pbc_3991330118",
      "name": "member_place_contributions",
      "type": "base",
      "system": false,
      "fields": [
        {
          "autogeneratePattern": "[a-z0-9]{15}",
          "help": "",
          "hidden": false,
          "id": "text3208210256",
          "max": 15,
          "min": 15,
          "name": "id",
          "pattern": "^[a-z0-9]+$",
          "presentable": false,
          "primaryKey": true,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "cascadeDelete": true,
          "collectionId": "pbc_2620428958",
          "help": "",
          "hidden": true,
          "id": "relation1894054520",
          "maxSelect": 1,
          "minSelect": 0,
          "name": "member",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "relation"
        },
        {
          "help": "",
          "hidden": false,
          "id": "select1602912115",
          "maxSelect": 1,
          "name": "source",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "select",
          "values": [
            "member_recommended"
          ]
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text2492862186",
          "max": 200,
          "min": 0,
          "name": "place_name",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": false,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text760939060",
          "max": 120,
          "min": 0,
          "name": "city",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": false,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text1400097126",
          "max": 120,
          "min": 0,
          "name": "country",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": false,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text223244161",
          "max": 300,
          "min": 0,
          "name": "address",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "help": "",
          "hidden": false,
          "id": "select105650625",
          "maxSelect": 1,
          "name": "category",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "select",
          "values": [
            "restaurant",
            "cafe",
            "bakery",
            "bar",
            "cocktail_bar",
            "wine_bar",
            "brewery",
            "food_market",
            "deli",
            "dessert_shop",
            "ice_cream",
            "takeaway",
            "other"
          ]
        },
        {
          "help": "",
          "hidden": false,
          "id": "select3420765984",
          "maxSelect": 14,
          "name": "occasions",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "select",
          "values": [
            "celebration",
            "casual_local_favorite",
            "coffee",
            "bakery",
            "drinks_nightcap",
            "neighborhood_meal",
            "date_night",
            "group_gathering",
            "quick_bite",
            "breakfast_brunch",
            "solo_friendly",
            "family_friendly",
            "late_night",
            "outdoor_seating"
          ]
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": true,
          "id": "text2990977895",
          "max": 2400,
          "min": 0,
          "name": "recommendation_note",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": false,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": true,
          "id": "text3600548136",
          "max": 240,
          "min": 0,
          "name": "normalized_name",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": false,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": true,
          "id": "text2783214874",
          "max": 160,
          "min": 0,
          "name": "normalized_city",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": false,
          "type": "text"
        },
        {
          "help": "",
          "hidden": false,
          "id": "select2063623452",
          "maxSelect": 1,
          "name": "status",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "select",
          "values": [
            "in_review",
            "approved",
            "rejected"
          ]
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": true,
          "id": "text1434203354",
          "max": 1200,
          "min": 0,
          "name": "curator_note",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "help": "",
          "hidden": false,
          "id": "date3494630457",
          "max": "",
          "min": "",
          "name": "reviewed_at",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "date"
        },
        {
          "hidden": false,
          "id": "autodate2990389176",
          "name": "created",
          "onCreate": true,
          "onUpdate": false,
          "presentable": false,
          "system": false,
          "type": "autodate"
        },
        {
          "hidden": false,
          "id": "autodate3332085495",
          "name": "updated",
          "onCreate": true,
          "onUpdate": true,
          "presentable": false,
          "system": false,
          "type": "autodate"
        }
      ],
      "indexes": [
        "CREATE INDEX `idx_member_place_contributions_member_status` ON `member_place_contributions` (member, status)",
        "CREATE INDEX `idx_member_place_contributions_city_status` ON `member_place_contributions` (city, status)",
        "CREATE UNIQUE INDEX `idx_member_place_contributions_open_place` ON `member_place_contributions` (normalized_name, normalized_city) WHERE status = 'in_review' OR status = 'approved'"
      ],
      "listRule": "(status = 'approved' && member.email !~ '%.invalid') || (@request.auth.id != '' && member = @request.auth.id)",
      "viewRule": "(status = 'approved' && member.email !~ '%.invalid') || (@request.auth.id != '' && member = @request.auth.id)",
      "createRule": null,
      "updateRule": null,
      "deleteRule": null
    },
    {
      "id": "pbc_2620428958",
      "name": "members",
      "type": "auth",
      "system": false,
      "fields": [
        {
          "autogeneratePattern": "[a-z0-9]{15}",
          "help": "",
          "hidden": false,
          "id": "text3208210256",
          "max": 15,
          "min": 15,
          "name": "id",
          "pattern": "^[a-z0-9]+$",
          "presentable": false,
          "primaryKey": true,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "cost": 0,
          "help": "",
          "hidden": true,
          "id": "password901924565",
          "max": 0,
          "min": 8,
          "name": "password",
          "pattern": "",
          "presentable": false,
          "required": true,
          "system": true,
          "type": "password"
        },
        {
          "autogeneratePattern": "[a-zA-Z0-9]{50}",
          "help": "",
          "hidden": true,
          "id": "text2504183744",
          "max": 60,
          "min": 30,
          "name": "tokenKey",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "exceptDomains": null,
          "help": "",
          "hidden": false,
          "id": "email3885137012",
          "name": "email",
          "onlyDomains": null,
          "presentable": false,
          "required": true,
          "system": true,
          "type": "email"
        },
        {
          "help": "",
          "hidden": false,
          "id": "bool1547992806",
          "name": "emailVisibility",
          "presentable": false,
          "required": false,
          "system": true,
          "type": "bool"
        },
        {
          "help": "",
          "hidden": false,
          "id": "bool256245529",
          "name": "verified",
          "presentable": false,
          "required": false,
          "system": true,
          "type": "bool"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text3578368839",
          "max": 100,
          "min": 0,
          "name": "display_name",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": false,
          "type": "text"
        },
        {
          "help": "",
          "hidden": false,
          "id": "select181047535",
          "maxSelect": 1,
          "name": "community_status",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "select",
          "values": [
            "unverified",
            "verified"
          ]
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text1864495378",
          "max": 80,
          "min": 0,
          "name": "invite_code",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "cascadeDelete": false,
          "collectionId": "pbc_2620428958",
          "help": "",
          "hidden": true,
          "id": "relation1109389909",
          "maxSelect": 1,
          "minSelect": 0,
          "name": "invited_by",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "relation"
        },
        {
          "cascadeDelete": false,
          "collectionId": "pbc_2452428166",
          "help": "",
          "hidden": true,
          "id": "relation3955152244",
          "maxSelect": 1,
          "minSelect": 0,
          "name": "redeemed_invite",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "relation"
        },
        {
          "help": "",
          "hidden": true,
          "id": "bool1437380409",
          "name": "founding_verified",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "bool"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text2261535133",
          "max": 30,
          "min": 0,
          "name": "pseudo",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "help": "",
          "hidden": false,
          "id": "bool3434413921",
          "name": "discovery_visible",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "bool"
        },
        {
          "help": "",
          "hidden": true,
          "id": "bool2516364040",
          "name": "founder_invitation_issuer",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "bool"
        },
        {
          "help": "",
          "hidden": true,
          "id": "bool661967594",
          "name": "direct_founder_invited",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "bool"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text209564667",
          "max": 120,
          "min": 0,
          "name": "home_city",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text3864199742",
          "max": 80,
          "min": 0,
          "name": "home_country",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "help": "",
          "hidden": true,
          "id": "bool3756178351",
          "name": "internal_member",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "bool"
        },
        {
          "help": "",
          "hidden": true,
          "id": "date2745685176",
          "max": "",
          "min": "",
          "name": "joined_at",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "date"
        }
      ],
      "indexes": [
        "CREATE UNIQUE INDEX `idx_tokenKey_pbc_2620428958` ON `members` (`tokenKey`)",
        "CREATE UNIQUE INDEX `idx_email_pbc_2620428958` ON `members` (`email`) WHERE `email` != ''",
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_members_redeemed_invite ON members (redeemed_invite) WHERE redeemed_invite != ''",
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_members_pseudo ON members (pseudo) WHERE pseudo != ''"
      ],
      "listRule": "@request.auth.id != '' && id = @request.auth.id",
      "viewRule": "@request.auth.id != '' && id = @request.auth.id",
      "createRule": "",
      "updateRule": "@request.auth.id != '' && id = @request.auth.id",
      "deleteRule": "@request.auth.id != '' && id = @request.auth.id",
      "authRule": "",
      "manageRule": null,
      "authAlert": {
        "enabled": true,
        "emailTemplate": {
          "subject": "Login from a new location",
          "body": "<p>Hello,</p>\n<p>We noticed a login to your {APP_NAME} account from a new location:</p>\n<p><em>{ALERT_INFO}</em></p>\n<p><strong>If this wasn't you, you should immediately change your {APP_NAME} account password to revoke access from all other locations.</strong></p>\n<p>If this was you, you may disregard this email.</p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>"
        }
      },
      "oauth2": {
        "providers": null,
        "mappedFields": {
          "id": "",
          "name": "",
          "username": "",
          "avatarURL": ""
        },
        "enabled": false
      },
      "passwordAuth": {
        "enabled": true,
        "identityFields": [
          "email"
        ]
      },
      "mfa": {
        "enabled": false,
        "duration": 600,
        "rule": ""
      },
      "otp": {
        "enabled": false,
        "duration": 180,
        "length": 8,
        "emailTemplate": {
          "subject": "OTP for {APP_NAME}",
          "body": "<p>Hello,</p>\n<p>Your one-time password is: <strong>{OTP}</strong></p>\n<p><i>If you didn't ask for the one-time password, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>"
        }
      },
      "authToken": {
        "secret": "FrCZO4kePLjxZuHWz6rsODOA1pJGDkGMk7WLctAqZ4pv4ccZOG",
        "duration": 432000
      },
      "passwordResetToken": {
        "secret": "3KGGcpt0jArCLKSW0dkT1wdEJ9g6IT4gbMZ4Jz2Ylx2k2HXBWe",
        "duration": 1800
      },
      "emailChangeToken": {
        "secret": "VrecREMKCbXBKPR7CVZ6cwC5wNP82Pm68Pe4dRJTTCrMGBqqgQ",
        "duration": 1800
      },
      "verificationToken": {
        "secret": "mpiHtXSe2jUDUep38vWbmbWOAfcaPhTWkrKF8jaPFvFQxdGK1f",
        "duration": 86400
      },
      "fileToken": {
        "secret": "jsExaCz5asZWpRyS6r6LSU02QSOV9qQVN1wovUsBE66OnjL02J",
        "duration": 180
      },
      "verificationTemplate": {
        "subject": "Verify your {APP_NAME} email",
        "body": "<p>Hello,</p>\n<p>Thank you for joining us at {APP_NAME}.</p>\n<p>Click on the button below to verify your email address.</p>\n<p>\n  <a class=\"btn\" href=\"{APP_URL}/_/#/auth/confirm-verification/{TOKEN}\" target=\"_blank\" rel=\"noopener\">Verify</a>\n</p>\n<p><i>If you didn't recently register, please ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>"
      },
      "resetPasswordTemplate": {
        "subject": "Reset your {APP_NAME} password",
        "body": "<p>Hello,</p>\n<p>Click on the button below to reset your password.</p>\n<p>\n  <a class=\"btn\" href=\"{APP_URL}/_/#/auth/confirm-password-reset/{TOKEN}\" target=\"_blank\" rel=\"noopener\">Reset password</a>\n</p>\n<p><i>If you didn't ask to reset your password, please ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>"
      },
      "confirmEmailChangeTemplate": {
        "subject": "Confirm your {APP_NAME} new email address",
        "body": "<p>Hello,</p>\n<p>Click on the button below to confirm your new email address.</p>\n<p>\n  <a class=\"btn\" href=\"{APP_URL}/_/#/auth/confirm-email-change/{TOKEN}\" target=\"_blank\" rel=\"noopener\">Confirm new email</a>\n</p>\n<p><i>If you didn't ask to change your email address, please ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>"
      }
    },
    {
      "id": "pbc_1379753955",
      "name": "venues",
      "type": "base",
      "system": false,
      "fields": [
        {
          "autogeneratePattern": "[a-z0-9]{15}",
          "help": "",
          "hidden": false,
          "id": "text3208210256",
          "max": 15,
          "min": 15,
          "name": "id",
          "pattern": "^[a-z0-9]+$",
          "presentable": false,
          "primaryKey": true,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text1579384326",
          "max": 200,
          "min": 0,
          "name": "name",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": false,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text760939060",
          "max": 120,
          "min": 0,
          "name": "city",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": false,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text1400097126",
          "max": 120,
          "min": 0,
          "name": "country",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": false,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text223244161",
          "max": 300,
          "min": 0,
          "name": "address",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "help": "",
          "hidden": false,
          "id": "number2499937429",
          "max": 90,
          "min": -90,
          "name": "lat",
          "onlyInt": false,
          "presentable": false,
          "required": false,
          "system": false,
          "type": "number"
        },
        {
          "help": "",
          "hidden": false,
          "id": "number2518964612",
          "max": 180,
          "min": -180,
          "name": "lng",
          "onlyInt": false,
          "presentable": false,
          "required": false,
          "system": false,
          "type": "number"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text105650625",
          "max": 120,
          "min": 0,
          "name": "category",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "exceptDomains": null,
          "help": "",
          "hidden": false,
          "id": "url4063379760",
          "name": "official_url",
          "onlyDomains": null,
          "presentable": false,
          "required": false,
          "system": false,
          "type": "url"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": true,
          "id": "text3468856390",
          "max": 300,
          "min": 0,
          "name": "coord_verification_note",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "hidden": false,
          "id": "autodate2990389176",
          "name": "created",
          "onCreate": true,
          "onUpdate": false,
          "presentable": false,
          "system": false,
          "type": "autodate"
        },
        {
          "hidden": false,
          "id": "autodate3332085495",
          "name": "updated",
          "onCreate": true,
          "onUpdate": true,
          "presentable": false,
          "system": false,
          "type": "autodate"
        },
        {
          "help": "",
          "hidden": false,
          "id": "bool68760273",
          "name": "approx_location",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "bool"
        },
        {
          "exceptDomains": null,
          "help": "",
          "hidden": false,
          "id": "url260122942",
          "name": "instagram_url",
          "onlyDomains": null,
          "presentable": false,
          "required": false,
          "system": false,
          "type": "url"
        },
        {
          "exceptDomains": null,
          "help": "",
          "hidden": false,
          "id": "url2895943165",
          "name": "image_url",
          "onlyDomains": null,
          "presentable": false,
          "required": false,
          "system": false,
          "type": "url"
        },
        {
          "help": "",
          "hidden": true,
          "id": "date2206743993",
          "max": "",
          "min": "",
          "name": "web_discovery_at",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "date"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": true,
          "id": "text304987509",
          "max": 300,
          "min": 0,
          "name": "web_discovery_note",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "help": "",
          "hidden": false,
          "id": "select3420765984",
          "maxSelect": 14,
          "name": "occasions",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "select",
          "values": [
            "celebration",
            "casual_local_favorite",
            "coffee",
            "bakery",
            "drinks_nightcap",
            "neighborhood_meal",
            "date_night",
            "group_gathering",
            "quick_bite",
            "breakfast_brunch",
            "solo_friendly",
            "family_friendly",
            "late_night",
            "outdoor_seating"
          ]
        },
        {
          "help": "",
          "hidden": false,
          "id": "bool1856513763",
          "name": "suppressed",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "bool"
        },
        {
          "help": "",
          "hidden": false,
          "id": "bool1748787223",
          "name": "published",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "bool"
        },
        {
          "help": "",
          "hidden": false,
          "id": "date3772055009",
          "max": "",
          "min": "",
          "name": "published_at",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "date"
        }
      ],
      "indexes": [
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_venues_name_city ON venues (name, city)",
        "CREATE INDEX IF NOT EXISTS idx_venues_city ON venues (city)"
      ],
      "listRule": "",
      "viewRule": "",
      "createRule": null,
      "updateRule": null,
      "deleteRule": null
    },
    {
      "id": "pbc_786234512",
      "name": "visit_evidence",
      "type": "base",
      "system": false,
      "fields": [
        {
          "autogeneratePattern": "[a-z0-9]{15}",
          "help": "",
          "hidden": false,
          "id": "text3208210256",
          "max": 15,
          "min": 15,
          "name": "id",
          "pattern": "^[a-z0-9]+$",
          "presentable": false,
          "primaryKey": true,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "cascadeDelete": true,
          "collectionId": "pbc_2620428958",
          "help": "",
          "hidden": false,
          "id": "relation1894054520",
          "maxSelect": 1,
          "minSelect": 0,
          "name": "member",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "relation"
        },
        {
          "cascadeDelete": false,
          "collectionId": "pbc_1379753955",
          "help": "",
          "hidden": false,
          "id": "relation2442205965",
          "maxSelect": 1,
          "minSelect": 0,
          "name": "venue",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "relation"
        },
        {
          "exceptDomains": null,
          "help": "",
          "hidden": false,
          "id": "url4121371955",
          "name": "evidence_url",
          "onlyDomains": null,
          "presentable": false,
          "required": false,
          "system": false,
          "type": "url"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text3485334036",
          "max": 1200,
          "min": 0,
          "name": "note",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": false,
          "type": "text"
        },
        {
          "help": "",
          "hidden": false,
          "id": "select2063623452",
          "maxSelect": 1,
          "name": "status",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "select",
          "values": [
            "pending",
            "approved",
            "rejected"
          ]
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": true,
          "id": "text1434203354",
          "max": 1200,
          "min": 0,
          "name": "curator_note",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "hidden": false,
          "id": "autodate2990389176",
          "name": "created",
          "onCreate": true,
          "onUpdate": false,
          "presentable": false,
          "system": false,
          "type": "autodate"
        },
        {
          "hidden": false,
          "id": "autodate3332085495",
          "name": "updated",
          "onCreate": true,
          "onUpdate": true,
          "presentable": false,
          "system": false,
          "type": "autodate"
        }
      ],
      "indexes": [
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_visit_evidence_member_venue ON visit_evidence (member, venue)",
        "CREATE INDEX IF NOT EXISTS idx_visit_evidence_member_status ON visit_evidence (member, status)"
      ],
      "listRule": "@request.auth.id != '' && member = @request.auth.id",
      "viewRule": "@request.auth.id != '' && member = @request.auth.id",
      "createRule": "@request.auth.id != ''",
      "updateRule": null,
      "deleteRule": null
    }
  ];

  // deleteMissing: false — never drop a collection this file does not list. The
  // platform-managed supernaut_* collections live in the same database.
  app.importCollections(collections, false);

  // PocketBase provisions its own default `users` auth collection on every clean
  // volume. Detour authenticates against `members` (invite-only, with community
  // status, pseudo, and founding provenance), so `users` is an unused public auth
  // surface that would otherwise reappear on every fresh install. Guarded: only
  // removed when it exists and is genuinely empty, so this can never delete real
  // accounts on an install that put them there.
  try {
    const users = app.findCollectionByNameOrId("users");
    if (app.countRecords(users.id) === 0) {
      app.delete(users);
      console.log("baseline schema: removed the unused default `users` collection");
    } else {
      console.log("baseline schema: default `users` collection has rows; left in place");
    }
  } catch {
    // Not present — nothing to remove.
  }
}, () => {
  // Forward-only: this is the schema baseline. Rolling it back would drop every
  // collection the app owns, including live member data.
  return null;
});
